[package]
name = "diff-crate-use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diff-a = {path = "./diff-a"}
diff-b = {path = "./diff-b"}
diff-c = {path = "./diff-c"}
